map $http_x_forwarded_proto $fwd_proto {
    default $http_x_forwarded_proto;
    ''      $scheme;
}

server {
    listen 80;
    server_name _;
    client_max_body_size 10m;
    server_tokens off;
    more_clear_headers Server;
    more_clear_headers X-Powered-By;

    error_page 404 500 502 503 504 /error.html;
    location = /error.html {
        root /usr/share/nginx/errors;
        internal;
        more_clear_headers Server;
    }

    location /api/ {
        proxy_pass http://api:8082;
        include /etc/nginx/proxy_api.conf;
    }

    location = /admin {
        proxy_pass http://api:8082;
        include /etc/nginx/proxy_api.conf;
    }

    location /admin/ {
        proxy_pass http://api:8082;
        include /etc/nginx/proxy_api.conf;
    }

    location /media/ {
        proxy_pass http://silo:9000/kryivka/;
        proxy_http_version 1.1;
        proxy_set_header Host silo:9000;
        proxy_set_header Authorization "";
        proxy_redirect off;
        proxy_hide_header Server;
        proxy_hide_header X-Powered-By;
        proxy_hide_header x-amz-request-id;
        proxy_hide_header x-amz-id-2;
        proxy_buffering off;
    }

    location / {
        return 404;
    }
}
